# Generated by Django 2.2.7 on 2020-03-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_i', models.TextField(max_length=250, verbose_name='من انا')),
                ('name', models.CharField(max_length=50, verbose_name='الإسم رابعى')),
                ('surname', models.CharField(max_length=20, verbose_name='اللقب')),
                ('subtitle', models.TextField(max_length=70, verbose_name='نبذه عنك')),
                ('address', models.CharField(max_length=30, verbose_name='المحافظه')),
                ('address_detail', models.CharField(max_length=25, verbose_name='العنوان بالتفصيل')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف')),
                ('number_phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('working_hours', models.CharField(max_length=50, verbose_name='عدد ساعات العمل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_image')),
                ('Waiting_time', models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('google', models.CharField(blank=True, max_length=100, null=True)),
                ('join_us', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانضمام')),
                ('type_doctors', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20, verbose_name='النوع')),
                ('doctor', models.CharField(choices=[('9', 'قلب واوعية دموية'), ('14', 'تخسيس وتغذية'), ('15', 'جراحة اطفال'), ('12', 'اورام'), ('16', 'جراحة اورام'), ('17', 'جراحة اوعية دموية'), ('19', 'جراحه سمنة ومناظير '), ('3', 'نفسي'), ('4', 'اطفال حديثي الولادة'), ('7', 'نساء وتوليد'), ('1', 'جلدية'), ('2', 'اسنان'), ('5', 'مخ واعصاب'), ('6', 'عظام'), ('8', 'انف واذن وحنجرة'), ('13', 'باطنه'), ('18', 'جراحة تجميل'), ('10', 'امراض دم')], max_length=50, verbose_name='دكتور ؟')),
                ('Specialist_doctor', models.CharField(max_length=50, verbose_name='متخصص فى ؟')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='التقييم')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='الإسم')),
                ('email', models.EmailField(max_length=50, verbose_name='الإيميل')),
                ('comments', models.TextField(max_length=250, verbose_name='التعليق')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_photos', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صور العياده :')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الإسم')),
                ('number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=50, verbose_name='الإيميل')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='doctor')),
            ],
        ),
    ]
