# Generated by Django 2.2.7 on 2020-03-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('7', 'نساء وتوليد'), ('15', 'جراحة اطفال'), ('4', 'اطفال حديثي الولادة'), ('18', 'جراحة تجميل'), ('3', 'نفسي'), ('12', 'اورام'), ('13', 'باطنه'), ('6', 'عظام'), ('8', 'انف واذن وحنجرة'), ('5', 'مخ واعصاب'), ('2', 'اسنان'), ('9', 'قلب واوعية دموية'), ('17', 'جراحة اوعية دموية'), ('16', 'جراحة اورام'), ('10', 'امراض دم'), ('1', 'جلدية'), ('19', 'جراحه سمنة ومناظير '), ('14', 'تخسيس وتغذية')], max_length=50, verbose_name='دكتور ؟'),
        ),
    ]
