# Generated by Django 2.2.7 on 2020-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200323_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('19', 'جراحه سمنة ومناظير '), ('4', 'اطفال حديثي الولادة'), ('3', 'نفسي'), ('16', 'جراحة اورام'), ('17', 'جراحة اوعية دموية'), ('13', 'باطنه'), ('1', 'جلدية'), ('7', 'نساء وتوليد'), ('15', 'جراحة اطفال'), ('18', 'جراحة تجميل'), ('14', 'تخسيس وتغذية'), ('5', 'مخ واعصاب'), ('2', 'اسنان'), ('8', 'انف واذن وحنجرة'), ('12', 'اورام'), ('9', 'قلب واوعية دموية'), ('6', 'عظام'), ('10', 'امراض دم')], max_length=50, verbose_name='دكتور ؟'),
        ),
    ]
