# Generated by Django 2.2.7 on 2020-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200323_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('17', 'جراحة اوعية دموية'), ('8', 'انف واذن وحنجرة'), ('12', 'اورام'), ('3', 'نفسي'), ('4', 'اطفال حديثي الولادة'), ('19', 'جراحه سمنة ومناظير '), ('16', 'جراحة اورام'), ('13', 'باطنه'), ('2', 'اسنان'), ('7', 'نساء وتوليد'), ('15', 'جراحة اطفال'), ('1', 'جلدية'), ('5', 'مخ واعصاب'), ('18', 'جراحة تجميل'), ('14', 'تخسيس وتغذية'), ('9', 'قلب واوعية دموية'), ('6', 'عظام'), ('10', 'امراض دم')], max_length=50, verbose_name='دكتور ؟'),
        ),
    ]
