# Generated by Django 3.0.7 on 2020-11-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200323_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='accounts.Profile', verbose_name='doctor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('قلب وأوعيه دموية', 'قلب وأوعيه دموية'), ('أنف وأذن وحنجرة', 'أنف وأذن وحنجرة'), ('أسنان', 'أسنان'), ('نفسي', 'نفسي'), ('أمراض دم', 'أمراض دم'), ('جراحة أطفال', 'جراحة أطفال'), ('نساء وتوليد', 'نساء وتوليد'), ('جراحة سمنة ومناظير ', 'جراحة سمنة ومناظير '), ('مخ وأعصاب', 'مخ وأعصاب'), ('جراحة أوعيه دموية', 'جراحة أوعيه دموية'), ('جراحة أورام', 'جراحة أورام'), ('عظام', 'عظام'), ('تخسيس وتغذية', 'تخسيس وتغذية'), ('جراحة تجميل', 'جراحة تجميل'), ('أورام', 'أورام'), ('جلدية', 'جلدية'), ('باطنة', 'باطنة'), ('أطفال حديثي الولادة', 'أطفال حديثي الولادة')], max_length=50, verbose_name='دكتور ؟'),
        ),
    ]
