# Generated by Django 2.2.7 on 2020-02-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='الصوره :')),
                ('short_description', models.CharField(max_length=250, verbose_name='عنولن مصغر ')),
                ('description', models.TextField(max_length=1000, verbose_name='المحتوى')),
                ('cretated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug :')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الإسم')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=50, verbose_name='الإيميل')),
                ('comments', models.TextField(max_length=250, verbose_name='التعليق')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-create_at',),
            },
        ),
    ]
