# Generated by Django 2.2.7 on 2020-02-11 22:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='most_advanced',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='المحتوى :'),
            preserve_default=False,
        ),
    ]
