# Generated by Django 2.2.7 on 2020-02-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200212_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='أنشاء فى :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=250, verbose_name='عنوان مصغر '),
        ),
    ]
