# Generated by Django 2.2.7 on 2020-02-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
