# Generated by Django 2.2.7 on 2020-02-19 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='doc_readed', to=settings.AUTH_USER_MODEL),
        ),
    ]
